### ISSUE TITLE
Game freezes up when clicking update link in About tab

### ISSUE THREAD

**Issue by yaomtc** [HereInPlainSight/gshade_installer#1] opened 2021-02-09 18:09 UTC
I'm not sure this script can do anything about this issue, but GShade itself doesn't have an issue tracker. I posted this on their Discord too.

I am playing with Proton 5.13-5 via Steam, but I just tested with the FFXIVQuickLauncher version on Lutris and it happens there too. (Weirdly I get constant seconds-long temporary freezes with that which I never saw with Proton. Haven't bothered to troubleshoot that.)

Certainly not an important issue, since the user should already have the script downloaded and has no need to visit the homepage to download the update. But I'm wondering if there could be an easy fix/workaround for this, or is the link making some system call that's unsupported by Wine? Should I file a bug on WineHQ?

**Comment by HereInPlainSight** [comment] 2021-02-15 17:43
Hey there!  The issue is that -- to my knowledge -- GShade tries to run an external program.  (Something in the `Program Files/GShade` folder, I believe.)  In order to make this work, we'd have to have something sitting there to replace it, and it would have to be in every wine prefix you installed GShade to.

Unfortunately, that's way outside the simple scripting I can provide -- or that I would think is reasonable -- nor could I guarantee that running something from inside wine that tries to perform updates on files outside of the wine prefix is going to work as intended.  I'm going to close the issue, but if anyone has any suggestions for a fix, I'd be happy to reopen it and discuss.

As for the freezes with Lutris, it's probably the mouse-lag issue mentioned in the pins in Discord.  Assuming that's the case, you can use the builds [here](https://drive.google.com/drive/folders/1t4ocQISQpuBCoa9NZdOOp4Ss6OvaItz9) to resolve.

**Closed as completed by HereInPlainSight** 2021-02-15 17:43 UTC

**Comment by yaomtc** [comment] 2021-02-15 18:42
Thanks for the info! I'll try that.
